---
title: "assignment"
author: "Paula Iller"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(epiwraps)
  library(rtracklayer)
  library(GenomicRanges)

})
ah <- AnnotationHub()
```


```{r}

# p300
download.file("https://www.encodeproject.org/files/ENCFF610ZFC/@@download/ENCFF610ZFC.bed.gz", dest="p300.bed.gz")
p300 <- rtracklayer::import("p300.bed.gz", format="narrowPeak")
head(p300)

# H3K4me3
download.file("https://www.encodeproject.org/files/ENCFF974BMC/@@download/ENCFF974BMC.bed.gz", dest="H3K4me3.bed.gz")
H3K4me3 <- rtracklayer::import("H3K4me3.bed.gz", format="narrowPeak")
head(H3K4me3)

# H3K4me1
download.file("https://www.encodeproject.org/files/ENCFF426IIV/@@download/ENCFF426IIV.bed.gz", dest="H3K4me1.bed.gz")
H3K4me1 <- rtracklayer::import("H3K4me1.bed.gz", format="narrowPeak")
head(H3K4me1)

# H3K27ac
download.file("https://www.encodeproject.org/files/ENCFF274UIB/@@download/ENCFF274UIB.bed.gz", dest="H3K27ac.bed.gz")
H3K27ac <- rtracklayer::import("H3K27ac.bed.gz", format="narrowPeak")
head(H3K27ac)

# H3K27me3
download.file("https://www.encodeproject.org/files/ENCFF008XKX/@@download/ENCFF008XKX.bed.gz", dest="H3K27me3.bed.gz")
H3K27me3 <- rtracklayer::import("H3K27me3.bed.gz", format="narrowPeak")
head(H3K27me3)

```

```{r} 
# How many p300 peaks overlap with promoters

# Check if any ranges in p300_peaks overlap with ranges in H3K4me3
Overlap_P300_H3K4me3 <- overlapsAny(query = p300, subject = H3K4me3)

# Summarize the overlaps
sum(Overlap_P300_H3K4me3)
# sum(Overlap_P300_H3K4me3) -> 10207

Overlap_P300_H3K4me1 <- overlapsAny(p300, H3K4me1)
# sum(Overlap_P300_H3K4me1) -> 4353

Overlap_P300_H3K27ac <- overlapsAny(p300, H3K27ac)
# sum(Overlap_P300_H3K27ac) -> 14699

Overlap_P300_H3K27me3 <- overlapsAny(p300, H3K27me3)
# sum(Overlap_P300_H3K27me3) -> 82



```

```{r} 
# Of the p300 peaks, what proportion overlap each of the mark
# Calculate proportions and round to the nearest integer
proportion1 <- round((sum(Overlap_P300_H3K4me3) / length(p300)) * 100, digits = 2)
proportion2 <- round((sum(Overlap_P300_H3K4me1) / length(p300)) * 100, digits = 2)
proportion3 <- round((sum(Overlap_P300_H3K27ac) / length(p300)) * 100, digits = 2)
proportion4 <- round((sum(Overlap_P300_H3K27me3) / length(p300)) * 100, digits = 2)

# Erstellen eines Dataframes für die Tabelle
data <- data.frame(
  Feature = c("H3K4me3", "H3K4me1", "H3K27ac", "H3K27me3"),
  Proportion = c(proportion1, proportion2, proportion3, proportion4)
)

# Tabelle anzeigen
knitr::kable(data, caption  = "Proportions of Overlap with P300 for the Different marks")


             
```
